#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  pkg ensure devel/py27-curses devel/py-curses

  block compile virtualenv

  ln -nfs "$shome/vendor/virtualenv/bin/clc" "$shome/bin/"
}

bootstrap
